export const SINGLE_FILE_LOADING = "SINGLE_FILE_LOADING"
export const SINGLE_FILE_LOADING_SUCCESS = "SINGLE_FILE_LOADING_SUCCESS"
export const SINGLE_FILE_LOADING_FAILURE = "SINGLE_FILE_LOADING_FAILURE"

export const ALL_FILES_LOADING = "ALL_FILES_LOADING"
export const ALL_FILES_LOADING_SUCCESS = "ALL_FILES_LOADING_SUCCESS"
export const ALL_FILES_LOADING_FAILURE = "ALL_FILES_LOADING_FAILURE"


export const UPLOAD_FILE_PROCESS = "UPLOAD_FILE_PROCESS"
export const UPLOAD_FILE_SUCCESS = "UPLOAD_FILE_SUCCESS"
export const UPLOAD_FILE_FAILURE = "UPLOAD_FILE_FAILURE"

export const DELETE_FILE_PROCESS = "DELETE_FILE_PROCESS"
export const DELETE_FILE_SUCCESS = "DELETE_FILE_SUCCESS"
export const DELETE_FILE_FAILURE = "DELETE_FILE_FAILURE"

export const MODIFY_FILE_NAME_PROCESS = "MODIFY_FILE_PROCESS"
export const MODIFY_FILE_NAME_SUCCESS = "MODIFY_FILE_SUCCESS"
export const MODIFY_FILE_NAME_FAILURE = "MODIFY_FILE_FAILURE"

export const DOWNLOAD_FILE_PROCESS = "DOWNLOAD_FILE_PROCESS"
export const DOWNLOAD_FILE_SUCCESS = "DOWNLOAD_FILE_SUCCESS"
export const DOWNLOAD_FILE_FAILURE = "DOWNLOAD_FILE_FAILURE"


