export const ALL_FILES_LOADING = "ALL_FILES_LOADING"
export const ALL_FILES_LOADING_SUCCESS = "ALL_FILES_LOADING_SUCCESS"
export const ALL_FILES_LOADING_FAILURE = "ALL_FILES_LOADING_FAILURE"

export const UPLOAD_FILE_PROCESS = "UPLOAD_FILE_PROCESS"
export const UPLOAD_FILE_SUCCESS = "UPLOAD_FILE_SUCCESS"
export const UPLOAD_FILE_FAILURE = "UPLOAD_FILE_FAILURE"

